# Load package

In [1]:
import scanpy as sc

import pandas as pd

# Load data

In [ ]:
test = sc.read('/Users/wenqchen/Desktop/Projects/Auria/Data/scRNA/scRNA_all.h5ad')

In [14]:
test.obs['subtype'].unique()

['HER2+', 'TNBC', 'ER+']
Categories (3, object): ['ER+', 'HER2+', 'TNBC']

In [ ]:
test_sub = test[test.obs['subtype'] == 'TNBC']
test_sub.obs

In [16]:
test.obs

,donor_id,percent_mito,nCount_RNA,nFeature_RNA,celltype_major,celltype_minor,celltype_subset,subtype,gene_module,calls,...,tissue_type,cell_type,assay,disease,organism,sex,tissue,self_reported_ethnicity,development_stage,observation_joinid
index,,,,,,,,,,,,,,,,,,,,,
CID3586_AAGACCTCAGCATGAG,CID3586,1.506221,4581,1689,Endothelial,Endothelial ACKR1,Endothelial ACKR1,HER2+,no_gene_module,no_scTYPER_call,...,tissue,endothelial cell,10x 5' v1,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,43-year-old human stage,{{GgYd(?F&
CID3586_AAGGTTCGTAGTACCT,CID3586,5.793743,1726,779,Endothelial,Endothelial ACKR1,Endothelial ACKR1,HER2+,no_gene_module,no_scTYPER_call,...,tissue,endothelial cell,10x 5' v1,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,43-year-old human stage,=x4pn{z@Fs
CID3586_ACCAGTAGTTGTGGCC,CID3586,1.383238,1229,514,Endothelial,Endothelial ACKR1,Endothelial ACKR1,HER2+,no_gene_module,no_scTYPER_call,...,tissue,endothelial cell,10x 5' v1,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,43-year-old human stage,a?omvd^>{v
CID3586_ACCCACTAGATGTCGG,CID3586,1.923077,1352,609,Endothelial,Endothelial ACKR1,Endothelial ACKR1,HER2+,no_gene_module,no_scTYPER_call,...,tissue,endothelial cell,10x 5' v1,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,43-year-old human stage,^@xqNME3NQ
CID3586_ACTGATGGTCAACTGT,CID3586,13.325541,1711,807,Endothelial,Endothelial ACKR1,Endothelial ACKR1,HER2+,no_gene_module,no_scTYPER_call,...,tissue,endothelial cell,10x 5' v1,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,43-year-old human stage,L&`nS{rJ{V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CID4398_TCAGGTAGTACTCAAC,CID4398,2.698336,6189,1251,Myeloid,DCs,Myeloid_c0_DC_LAMP3,ER+,no_gene_module,no_scTYPER_call,...,tissue,myeloid cell,10x 3' v2,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,52-year-old human stage,2Y_#4kbhQx
CID4398_TCTATTGTCGCCATAA,CID4398,3.057905,4611,719,Myeloid,DCs,Myeloid_c0_DC_LAMP3,ER+,no_gene_module,no_scTYPER_call,...,tissue,myeloid cell,10x 3' v2,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,52-year-old human stage,^yoB{d`wt7
CID4398_TCTTTCCCAGTAAGCG,CID4398,3.682625,2987,887,Myeloid,DCs,Myeloid_c0_DC_LAMP3,ER+,no_gene_module,no_scTYPER_call,...,tissue,myeloid cell,10x 3' v2,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,52-year-old human stage,;ZsdmlD;vK
CID4398_TGCCCATGTTACGGAG,CID4398,2.208325,5117,870,Myeloid,DCs,Myeloid_c0_DC_LAMP3,ER+,no_gene_module,no_scTYPER_call,...,tissue,myeloid cell,10x 3' v2,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,52-year-old human stage,OhbcYGg7wg
CID4398_TTGAACGTCCTATTCA,CID4398,2.126067,6679,1231,Myeloid,DCs,Myeloid_c0_DC_LAMP3,ER+,no_gene_module,no_scTYPER_call,...,tissue,myeloid cell,10x 3' v2,invasive ductal breast carcinoma,Homo sapiens,female,breast,unknown,52-year-old human stage,OR}Fuca*bu

In [2]:
adata = sc.read('/Users/wenqchen/Desktop/Projects/Auria/Data/scRNA/TNBC_adata.h5ad')

In [3]:
adata.obs

,orig.ident,nCount_RNA,nFeature_RNA,NAME,Patient,Percent_mito,celltype_major,celltype_minor,celltype_subset,subtype,...,CNA_value,oxstress,treatment,age,cancer_type,GCLCVIM,signature_GCLCVIM,signature_GCLCVIMTUMOR,signature_anastasis,signature_proliferation
CID4465_AAACGGGTCATCGATG,CID4465,1277,799,CID4465_AAACGGGTCATCGATG,CID4465,2.662490,Endothelial,Endothelial ACKR1,Endothelial ACKR1,TNBC,...,no_CNA_value,0.063201,Naïve,54,IDC,-+,0.176422,0.176843,0.331157,-0.036520
CID4465_AAACGGGTCGGAAACG,CID4465,478,339,CID4465_AAACGGGTCGGAAACG,CID4465,3.556485,Endothelial,Endothelial ACKR1,Endothelial ACKR1,TNBC,...,no_CNA_value,0.075607,Naïve,54,IDC,-+,0.095979,0.114641,0.521046,-0.008995
CID4465_AAAGATGAGGTGTGGT,CID4465,1495,878,CID4465_AAAGATGAGGTGTGGT,CID4465,3.879599,Endothelial,Endothelial ACKR1,Endothelial ACKR1,TNBC,...,no_CNA_value,0.111242,Naïve,54,IDC,--,0.115277,0.126621,0.617526,-0.024047
CID4465_AAAGCAATCCTTTACA,CID4465,723,457,CID4465_AAAGCAATCCTTTACA,CID4465,3.181189,Endothelial,Endothelial ACKR1,Endothelial ACKR1,TNBC,...,no_CNA_value,0.044548,Naïve,54,IDC,--,0.039549,0.050179,0.491101,-0.055846
CID4465_AACCATGGTACGCTGC,CID4465,1977,1074,CID4465_AACCATGGTACGCTGC,CID4465,6.120384,Endothelial,Endothelial ACKR1,Endothelial ACKR1,TNBC,...,no_CNA_value,0.113377,Naïve,54,IDC,-+,0.131447,0.130072,0.435326,-0.064722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CID3963_GAACCTACACAGATTC,CID3963,1316,566,CID3963_GAACCTACACAGATTC,CID3963,0.303951,Cancer Epithelial,Cancer LumA SC,Cancer LumA SC,TNBC,...,0.280199512,0.082146,Treated,61,IDC,--,0.082191,0.171436,-0.308466,-0.001009
CID3963_GCATGCGGTTCGAATC,CID3963,1372,575,CID3963_GCATGCGGTTCGAATC,CID3963,0.437318,Cancer Epithelial,Cancer LumA SC,Cancer LumA SC,TNBC,...,0.231542891,0.204991,Treated,61,IDC,--,0.020497,0.092769,-0.302699,0.045975
CID3963_GTACGTAGTGAGGGAG,CID3963,3247,1167,CID3963_GTACGTAGTGAGGGAG,CID3963,14.875269,Cancer Epithelial,Cancer LumA SC,Cancer LumA SC,TNBC,...,0.298488317,0.142501,Treated,61,IDC,--,0.104554,0.180978,0.353898,-0.004652
CID3963_TATTACCTCTTACCTA,CID3963,6043,1712,CID3963_TATTACCTCTTACCTA,CID3963,15.224226,Cancer Epithelial,Cancer Her2 SC,Cancer Her2 SC,TNBC,...,0.228002684,0.152117,Treated,61,IDC,--,0.067952,0.145327,1.345855,0.006607
CID3963_TTCTCCTTCCACGACG,CID3963,2814,1029,CID3963_TTCTCCTTCCACGACG,CID3963,17.945984,Cancer Epithelial,Cancer Her2 SC,Cancer Her2 SC,TNBC,...,0.392383032,0.104252,Treated,61,IDC,--,0.055921,0.133968,0.911988,-0.039944

In [5]:
adata.obs['subtype'].unique()

['TNBC']
Categories (1, object): ['TNBC']

In [ ]:
adata.uns.spatial

In [6]:
adata.obs

,array_row,array_col,tumour_cells,EMT,EPI,batch,B_cells_Memory,B_cells_Naive,CAFs_MSC_iCAF-like_s1,CAFs_MSC_iCAF-like_s2,...,Cancer_total,Endothelial_total,Luminal_total,Myeloid_total,Myoepithelia_total,PVL_total,TCD4_total,TCD8_total,NK_total,Plasmablasts_total
AAACAACGAATAGTTC-1_1160920F-7-7,0,16,1.0,0.045052,0.317959,7,0.145060,0.059700,0.114736,0.007786,...,0.608084,0.005953,0.105584,0.058866,0.024988,0.005979,0.028345,0.044177,0.012390,0.045892
AAACAAGTATCTCCCA-1_1142243F-10-10,50,102,NaN,0.050492,0.351666,10,0.363685,0.200781,0.105437,0.014676,...,0.341987,0.045077,0.019124,0.088229,0.013075,0.008578,0.109227,0.172739,0.050670,0.018254
AAACAAGTATCTCCCA-1_1160920F-7-7,50,102,1.0,0.042293,0.371749,7,0.001542,0.001350,0.000107,0.000319,...,0.858368,0.000370,0.096974,0.022403,0.001296,0.000311,0.001305,0.001697,0.001530,0.014933
AAACAAGTATCTCCCA-1_CID4465-6-6,50,102,NaN,0.012409,0.006795,6,1.560966,0.807271,6.009028,0.107440,...,0.005725,0.050728,0.003435,0.146194,0.018368,0.042825,0.097766,0.111667,0.040765,0.014745
AAACAATCTACTAGCA-1_1160920F-7-7,3,43,1.0,0.025001,0.323979,7,0.017783,0.012296,0.057236,0.002019,...,0.819858,0.005089,0.043011,0.034721,0.004245,0.001917,0.008083,0.024636,0.006637,0.024020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTTTGTATTACACG-1_1160920F-7-7,73,41,1.0,0.114186,0.254868,7,0.094742,0.045621,0.007759,0.003298,...,0.533756,0.001121,0.036027,0.193277,0.001595,0.002048,0.049389,0.061957,0.037439,0.023247
TTGTTTGTGTAAATTC-1_1142243F-10-10,7,51,1.0,0.074914,0.297338,10,0.018835,0.015934,0.009066,0.004739,...,0.803138,0.003002,0.064161,0.033067,0.007716,0.003434,0.017539,0.025681,0.006224,0.003948
TTGTTTGTGTAAATTC-1_1160920F-7-7,7,51,1.0,0.046544,0.224156,7,0.182396,0.101474,0.027570,0.006445,...,0.372726,0.002580,0.017770,0.306268,0.002379,0.001048,0.072293,0.086710,0.025282,0.005446
TTGTTTGTGTAAATTC-1_CID4465-6-6,7,51,1.0,0.064207,0.182106,6,0.008835,0.005342,0.038148,0.003993,...,0.252034,0.106914,0.002658,0.113768,0.001278,0.210800,0.009580,0.014191,0.005332,0.138934
TTGTTTGTGTAAATTC-1_CID44971-9-9,7,51,NaN,0.024647,0.461778,9,0.029801,0.015500,0.529673,0.011653,...,0.286156,0.014291,0.081441,0.039247,0.232179,0.015835,0.029132,0.039040,0.010604,0.003644

In [11]:
test

AnnData object with n_obs × n_vars = 11971 × 14664
    obs: 'array_row', 'array_col', 'tumour_cells', 'EMT', 'EPI', 'batch', 'B_cells_Memory', 'B_cells_Naive', 'CAFs_MSC_iCAF-like_s1', 'CAFs_MSC_iCAF-like_s2', 'CAFs_Transitioning_s3', 'CAFs_myCAF_like_s4', 'CAFs_myCAF_like_s5', 'Cancer_Basal_SC_0', 'Cancer_Basal_SC_1', 'Cancer_Basal_SC_2', 'Cancer_Cycling_0', 'Cancer_Cycling_1', 'Cancer_Cycling_2', 'Cancer_Her2_SC_0', 'Cancer_Her2_SC_1', 'Cancer_Her2_SC_2', 'Cancer_LumA_SC_0', 'Cancer_LumA_SC_1', 'Cancer_LumA_SC_2', 'Cancer_LumB_SC_0', 'Cancer_LumB_SC_1', 'Cancer_LumB_SC_2', 'Cycling_PVL', 'Cycling_Myeloid', 'Endothelial_ACKR1', 'Endothelial_CXCL12', 'Endothelial_Lymphatic_LYVE1', 'Endothelial_RGS5', 'Luminal_Progenitors_0', 'Luminal_Progenitors_1', 'Luminal_Progenitors_2', 'Mature_Luminal_0', 'Mature_Luminal_1', 'Mature_Luminal_2', 'Myeloid_c0_DC_LAMP3', 'Myeloid_c10_Macrophage_1_EGR1', 'Myeloid_c11_cDC2_CD1C', 'Myeloid_c12_Monocyte_1_IL1B', 'Myeloid_c1_LAM1_FABP5', 'Myeloid_c2_LAM2_APOE', 'Myeloid_c3_cDC1_CLEC9A', 'Myeloid_c4_DCs_pDC_IRF7', 'Myeloid_c5_Macrophage_3_SIGLEC1', 'Myeloid_c7_Monocyte_3_FCGR3A', 'Myeloid_c8_Monocyte_2_S100A9', 'Myeloid_c9_Macrophage_2_CXCL10', 'Myoepithelial_0', 'Myoepithelial_2', 'PVL_Differentiated_s3', 'PVL_Immature_s1', 'PVL_Immature_s2', 'Plasmablasts', 'T_cells_c0_CD4+_CCR7', 'T_cells_c10_NKT_cells_FCGR3A', 'T_cells_c11_MKI67', 'T_cells_c1_CD4+_IL7R', 'T_cells_c2_CD4+_T-regs_FOXP3', 'T_cells_c3_CD4+_Tfh_CXCL13', 'T_cells_c4_CD8+_ZFP36', 'T_cells_c5_CD8+_GZMK', 'T_cells_c6_IFIT1', 'T_cells_c7_CD8+_IFNG', 'T_cells_c8_CD8+_LAG3', 'T_cells_c9_NK_cells_AREG', 'oxstress', 'GCLC_VIM', 'B cells Memory_norm', 'B cells Naive_norm', 'CAFs MSC iCAF-like s1_norm', 'CAFs MSC iCAF-like s2_norm', 'CAFs Transitioning s3_norm', 'CAFs myCAF like s4_norm', 'CAFs myCAF like s5_norm', 'Cancer Basal SC_0_norm', 'Cancer Basal SC_1_norm', 'Cancer Basal SC_2_norm', 'Cancer Cycling_0_norm', 'Cancer Cycling_1_norm', 'Cancer Cycling_2_norm', 'Cancer Her2 SC_0_norm', 'Cancer Her2 SC_1_norm', 'Cancer Her2 SC_2_norm', 'Cancer LumA SC_0_norm', 'Cancer LumA SC_1_norm', 'Cancer LumA SC_2_norm', 'Cancer LumB SC_0_norm', 'Cancer LumB SC_1_norm', 'Cancer LumB SC_2_norm', 'Cycling PVL_norm', 'Cycling_Myeloid_norm', 'Endothelial ACKR1_norm', 'Endothelial CXCL12_norm', 'Endothelial Lymphatic LYVE1_norm', 'Endothelial RGS5_norm', 'Luminal Progenitors_0_norm', 'Luminal Progenitors_1_norm', 'Luminal Progenitors_2_norm', 'Mature Luminal_0_norm', 'Mature Luminal_1_norm', 'Mature Luminal_2_norm', 'Myeloid_c0_DC_LAMP3_norm', 'Myeloid_c10_Macrophage_1_EGR1_norm', 'Myeloid_c11_cDC2_CD1C_norm', 'Myeloid_c12_Monocyte_1_IL1B_norm', 'Myeloid_c1_LAM1_FABP5_norm', 'Myeloid_c2_LAM2_APOE_norm', 'Myeloid_c3_cDC1_CLEC9A_norm', 'Myeloid_c4_DCs_pDC_IRF7_norm', 'Myeloid_c5_Macrophage_3_SIGLEC1_norm', 'Myeloid_c7_Monocyte_3_FCGR3A_norm', 'Myeloid_c8_Monocyte_2_S100A9_norm', 'Myeloid_c9_Macrophage_2_CXCL10_norm', 'Myoepithelial_0_norm', 'Myoepithelial_2_norm', 'PVL Differentiated s3_norm', 'PVL Immature s1_norm', 'PVL_Immature s2_norm', 'Plasmablasts_norm', 'T_cells_c0_CD4+_CCR7_norm', 'T_cells_c10_NKT_cells_FCGR3A_norm', 'T_cells_c11_MKI67_norm', 'T_cells_c1_CD4+_IL7R_norm', 'T_cells_c2_CD4+_T-regs_FOXP3_norm', 'T_cells_c3_CD4+_Tfh_CXCL13_norm', 'T_cells_c4_CD8+_ZFP36_norm', 'T_cells_c5_CD8+_GZMK_norm', 'T_cells_c6_IFIT1_norm', 'T_cells_c7_CD8+_IFNG_norm', 'T_cells_c8_CD8+_LAG3_norm', 'T_cells_c9_NK_cells_AREG_norm', 'nan_norm'
    var: 'mt', 'n_cells_by_counts-0', 'mean_counts-0', 'log1p_mean_counts-0', 'pct_dropout_by_counts-0', 'total_counts-0', 'log1p_total_counts-0', 'n_cells_by_counts-1', 'mean_counts-1', 'log1p_mean_counts-1', 'pct_dropout_by_counts-1', 'total_counts-1', 'log1p_total_counts-1', 'n_cells_by_counts-10', 'mean_counts-10', 'log1p_mean_counts-10', 'pct_dropout_by_counts-10', 'total_counts-10', 'log1p_total_counts-10', 'n_cells_by_counts-11', 'mean_counts-11', 'log1p_mean_counts-11', 'pct_dropout_by_counts-11', 'total_counts-11', 'log1p_total_counts-11', 'n_cells_by_counts-2', 'mean_counts-2', 'log1p_mean_counts-2', 'pct_dropout_by_counts-2', 'total_counts-2', 'log1p_total_counts-2', 'n_cells_by_counts-3', 'mean_counts-3', 'log1p_mean_counts-3', 'pct_dropout_by_counts-3', 'total_counts-3', 'log1p_total_counts-3', 'n_cells_by_counts-4', 'mean_counts-4', 'log1p_mean_counts-4', 'pct_dropout_by_counts-4', 'total_counts-4', 'log1p_total_counts-4', 'n_cells_by_counts-5', 'mean_counts-5', 'log1p_mean_counts-5', 'pct_dropout_by_counts-5', 'total_counts-5', 'log1p_total_counts-5', 'n_cells_by_counts-6', 'mean_counts-6', 'log1p_mean_counts-6', 'pct_dropout_by_counts-6', 'total_counts-6', 'log1p_total_counts-6', 'n_cells_by_counts-7', 'mean_counts-7', 'log1p_mean_counts-7', 'pct_dropout_by_counts-7', 'total_counts-7', 'log1p_total_counts-7', 'n_cells_by_counts-8', 'mean_counts-8', 'log1p_mean_counts-8', 'pct_dropout_by_counts-8', 'total_counts-8', 'log1p_total_counts-8', 'n_cells_by_counts-9', 'mean_counts-9', 'log1p_mean_counts-9', 'pct_dropout_by_counts-9', 'total_counts-9', 'log1p_total_counts-9'
    uns: 'spatial'
    obsm: 'MT', 'deconvolution_results', 'normalized_deconv_results', 'q05_cell_abundance_w_sf', 'spatial'

In [12]:
test.var

,mt,n_cells_by_counts-0,mean_counts-0,log1p_mean_counts-0,pct_dropout_by_counts-0,total_counts-0,log1p_total_counts-0,n_cells_by_counts-1,mean_counts-1,log1p_mean_counts-1,...,log1p_mean_counts-8,pct_dropout_by_counts-8,total_counts-8,log1p_total_counts-8,n_cells_by_counts-9,mean_counts-9,log1p_mean_counts-9,pct_dropout_by_counts-9,total_counts-9,log1p_total_counts-9
SAMD11,False,94,0.043292,0.042381,95.970853,101.0,4.624973,1,0.001255,0.001254,...,0.198837,82.360197,535.0,6.284134,35,0.031842,0.031345,96.987952,37.0,3.637586
NOC2L,False,789,0.530647,0.425691,66.180883,1238.0,7.122060,51,0.071518,0.069077,...,0.293013,72.327303,828.0,6.720220,496,0.641136,0.495389,57.314974,745.0,6.614726
KLHL17,False,235,0.117017,0.110661,89.927132,273.0,5.613128,24,0.030113,0.029668,...,0.102313,90.090461,262.0,5.572154,154,0.148021,0.138039,86.746988,172.0,5.153292
PLEKHN1,False,23,0.009859,0.009810,99.014145,23.0,3.178054,4,0.005019,0.005006,...,0.054024,94.860197,135.0,4.912655,28,0.024096,0.023811,97.590361,28.0,3.367296
PERM1,False,11,0.004715,0.004704,99.528504,11.0,2.484907,2,0.002509,0.002506,...,0.035942,96.587171,89.0,4.499810,3,0.002582,0.002578,99.741824,3.0,1.386294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C21orf58,False,68,0.030433,0.029979,97.085298,71.0,4.276666,10,0.012547,0.012469,...,0.039901,96.052632,99.0,4.605170,58,0.053356,0.051982,95.008606,62.0,4.143135
PCNT,False,240,0.119589,0.112961,89.712816,279.0,5.634789,30,0.042660,0.041775,...,0.134816,87.458882,351.0,5.863631,284,0.317556,0.275778,75.559380,369.0,5.913503
DIP2A,False,411,0.213030,0.193122,82.383198,497.0,6.210600,38,0.055207,0.053737,...,0.204216,80.797697,551.0,6.313548,323,0.360585,0.307915,72.203098,419.0,6.040255
S100B,False,258,0.156022,0.144985,88.941277,364.0,5.899898,0,0.000000,0.000000,...,0.015909,98.478618,39.0,3.688879,223,0.269363,0.238515,80.808950,313.0,5.749393
PRMT2,False,809,0.566224,0.448667,65.323618,1321.0,7.186901,81,0.112923,0.106990,...,0.439421,62.171053,1342.0,7.202661,699,1.194492,0.785951,39.845095,1388.0,7.236340

In [10]:
test.obs

,array_row,array_col,tumour_cells,EMT,EPI,batch,B_cells_Memory,B_cells_Naive,CAFs_MSC_iCAF-like_s1,CAFs_MSC_iCAF-like_s2,...,T_cells_c1_CD4+_IL7R_norm,T_cells_c2_CD4+_T-regs_FOXP3_norm,T_cells_c3_CD4+_Tfh_CXCL13_norm,T_cells_c4_CD8+_ZFP36_norm,T_cells_c5_CD8+_GZMK_norm,T_cells_c6_IFIT1_norm,T_cells_c7_CD8+_IFNG_norm,T_cells_c8_CD8+_LAG3_norm,T_cells_c9_NK_cells_AREG_norm,nan_norm
AAACAACGAATAGTTC-1_1160920F-7-7,0,16,1.0,0.045052,0.317959,7,0.145060,0.059700,0.114736,0.007786,...,0.003961,0.009000,0.007662,0.003367,0.029572,0.020447,0.004494,0.005698,0.003103,0.002177
AAACAAGTATCTCCCA-1_1142243F-10-10,50,102,NaN,0.050492,0.351666,10,0.363685,0.200781,0.105437,0.014676,...,0.011626,0.032283,0.027612,0.009369,0.115613,0.059931,0.015210,0.020517,0.010092,0.002814
AAACAAGTATCTCCCA-1_1160920F-7-7,50,102,1.0,0.042293,0.371749,7,0.001542,0.001350,0.000107,0.000319,...,0.000474,0.000179,0.000350,0.000397,0.000568,0.000571,0.000414,0.000313,0.000626,0.002492
AAACAAGTATCTCCCA-1_CID4465-6-6,50,102,NaN,0.012409,0.006795,6,1.560966,0.807271,6.009028,0.107440,...,0.011091,0.030030,0.025380,0.007987,0.074290,0.045047,0.010981,0.013227,0.008680,0.000276
AAACAATCTACTAGCA-1_1160920F-7-7,3,43,1.0,0.025001,0.323979,7,0.017783,0.012296,0.057236,0.002019,...,0.001690,0.001848,0.002343,0.001840,0.017290,0.006694,0.003016,0.002232,0.001954,0.001595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTGTTTGTATTACACG-1_1160920F-7-7,73,41,1.0,0.114186,0.254868,7,0.094742,0.045621,0.007759,0.003298,...,0.003609,0.017388,0.013718,0.003819,0.030082,0.126741,0.005692,0.014216,0.004868,0.002068
TTGTTTGTGTAAATTC-1_1142243F-10-10,7,51,1.0,0.074914,0.297338,10,0.018835,0.015934,0.009066,0.004739,...,0.003930,0.004309,0.004557,0.003579,0.013871,0.010289,0.003524,0.004264,0.002755,0.004424
TTGTTTGTGTAAATTC-1_1160920F-7-7,7,51,1.0,0.046544,0.224156,7,0.182396,0.101474,0.027570,0.006445,...,0.007087,0.017917,0.027990,0.005188,0.053556,0.038790,0.010452,0.013904,0.005978,0.000891
TTGTTTGTGTAAATTC-1_CID4465-6-6,7,51,1.0,0.064207,0.182106,6,0.008835,0.005342,0.038148,0.003993,...,0.002246,0.002071,0.002520,0.001593,0.005838,0.003809,0.002633,0.004026,0.001192,0.000809
TTGTTTGTGTAAATTC-1_CID44971-9-9,7,51,NaN,0.024647,0.461778,9,0.029801,0.015500,0.529673,0.011653,...,0.004472,0.009937,0.007010,0.002744,0.028941,0.010845,0.003107,0.003628,0.003848,0.004060