# Load package

In [1]:
import scimap as sm

import sys
import anndata as ad
import seaborn as sns; sns.set(color_codes=True)
import numpy as np

import scanpy as sc
import pandas as pd
import matplotlib.pyplot as plt

Running SCIMAP  2.2.11

# Load data

In [2]:
data = pd.read_csv('/Users/wenqchen/Desktop/Projects/Auria/Data/t-CycIF/Data_AllMarkers_filtered_2.csv', index_col=0)

/var/folders/rq/68pl8_s15_lc84mft22mqf012ws2td/T/ipykernel_91771/1910434769.py:1: DtypeWarning:

Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.

In [4]:
data.columns

Index(['S9.6', 'HER3', 'panCK', 'SMA', 'CD45', 'Ki67_2', 'CD4', 'FOXP3',
       'CD8a', 'CD11b', 'CD68', 'CD206', 'H2ax', 'Vimentin', 'H3K27me3',
       'E.Cadherin', 'GCLC', 'TXNRD1', 'NQO1', 'pERK', 'TXN', 'pSTAT3',
       'pS6_235', 'pRB', 'GLUT1', 'X_centroid', 'Y_centroid', 'imageid',
       'core_imageid', 'cores.x', 'celltype', 'Annotation', 'Stage',
       'patient_id_AB19_1654', 'Area', 'Eccentricity', 'antioxidant_NQOI',
       'antioxidant_GCLC', 'antioxidant_TXNRD1', 'antioxidant_GLUT1',
       'NQO1_GCLC_VIM', 'celltype_2', 'celltype_1', 'Tumor_state', 'GCLC_VIM',
       'CellCategory'],
      dtype='object')

In [ ]:
data

In [3]:
data

,S9.6,HER3,panCK,SMA,CD45,Ki67_2,CD4,FOXP3,CD8a,CD11b,...,antioxidant_NQOI,antioxidant_GCLC,antioxidant_TXNRD1,antioxidant_GLUT1,NQO1_GCLC_VIM,celltype_2,celltype_1,Tumor_state,GCLC_VIM,CellCategory
CellID,,,,,,,,,,,,,,,,,,,,,
1,0.587351,0.668424,0.197573,0.119095,0.357855,0.221494,0.351031,0.261670,0.120537,0.641891,...,failed_classify,failed_classify,failed_classify,failed_classify,---,Other,Other.Stroma,Other.Stroma,Other.Stroma,Stroma
10,0.711467,0.738836,0.522747,0.185507,0.275963,0.214838,0.374685,0.350623,0.029450,0.608733,...,NQO1_pos,failed_classify,TXNRD1_pos,failed_classify,+--,Tumor_+--,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor
10,0.803970,0.824031,0.331924,0.204348,0.355699,0.234078,0.518679,0.390894,0.161177,0.666724,...,NQO1_pos,failed_classify,failed_classify,failed_classify,+--,CD68.Macrophages,CD68.Macrophages,CD68.Macrophages,CD68.Macrophages,Immune
100,0.744246,0.762114,0.531392,0.185345,0.246533,0.227313,0.392369,0.348677,0.023832,0.619029,...,NQO1_pos,failed_classify,TXNRD1_pos,failed_classify,+--,Tumor_+--,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor
100,0.796639,0.796858,0.357244,0.192493,0.431782,0.228827,0.489430,0.380457,0.156145,0.674359,...,failed_classify,failed_classify,failed_classify,failed_classify,---,Immune,Other.Immune,Other.Immune,Other.Immune,Immune
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99998,0.832069,0.723583,0.638020,0.130660,0.135379,0.173406,0.316902,0.220026,0.366662,0.634752,...,failed_classify,failed_classify,failed_classify,failed_classify,---,Tumor_---,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor
99999,0.770561,0.929819,0.451729,0.390374,0.620998,0.488494,0.532568,0.522331,0.467017,0.871813,...,failed_classify,GCLC_pos,failed_classify,failed_classify,-++,FOXP3.CD4.Tregs,Treg,Treg,Treg,Immune
99999,0.678946,0.721054,0.228812,0.598502,0.598347,0.229858,0.528080,0.499220,0.232839,0.704152,...,failed_classify,GCLC_pos,failed_classify,failed_classify,-++,CD4.T.cells,CD4.T.cells,CD4.T.cells,CD4.T.cells,Immune
99999,0.845231,0.699380,0.353627,0.224872,0.146464,0.184371,0.271080,0.261490,0.140438,0.615633,...,failed_classify,failed_classify,failed_classify,failed_classify,---,Tumor_---,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor
99999,0.733093,0.744165,0.681137,0.123724,0.095359,0.169273,0.324368,0.219458,0.318816,0.638407,...,failed_classify,failed_classify,failed_classify,failed_classify,---,Tumor_---,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor

# Spatial Count

In [4]:
image_path = '/Users/wenqchen/Desktop/Projects/Auria/Data/t-CycIF/Data_AllMarkers_filtered_2.csv'
# Convert the data to scimap format
adata = sm.pp.mcmicro_to_scimap(image_path, 
                                remove_dna=False, remove_string_from_name=None, log=False, drop_markers=None,
                                random_sample=None, unique_CellId=True, CellId='CellID', split='X_centroid',
                                custom_imageid=None, min_cells=None, output_dir=None)
adata.obsm['spatial'] = np.array(adata.obs[['Y_centroid', 'X_centroid']])
adata

Loading Data_AllMarkers_filtered_2.csv

/Users/wenqchen/miniconda/envs/napari-env/lib/python3.10/site-packages/scimap/preprocessing/mcmicro_to_scimap.py:106: DtypeWarning:

Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.

AnnData object with n_obs × n_vars = 3681772 × 25
    obs: 'X_centroid', 'Y_centroid', 'core_imageid', 'cores.x', 'celltype', 'Annotation', 'Stage', 'patient_id_AB19_1654', 'Area', 'Eccentricity', 'antioxidant_NQOI', 'antioxidant_GCLC', 'antioxidant_TXNRD1', 'antioxidant_GLUT1', 'NQO1_GCLC_VIM', 'celltype_2', 'celltype_1', 'Tumor_state', 'GCLC_VIM', 'CellCategory', 'CellID', 'imageid'
    uns: 'all_markers'
    obsm: 'spatial'

In [5]:
adata = sm.tl.spatial_count(adata, phenotype='celltype_1', method='radius', radius=45, label='spatial_count_45px')

Identifying neighbours within 45 pixels of every cell
Identifying neighbours within 45 pixels of every cell
Identifying neighbours within 45 pixels of every cell
Identifying neighbours within 45 pixels of every cell
Identifying neighbours within 45 pixels of every cell
Identifying neighbours within 45 pixels of every cell
Identifying neighbours within 45 pixels of every cell
Identifying neighbours within 45 pixels of every cell
Identifying neighbours within 45 pixels of every cell

In [6]:
adata = sm.tl.spatial_cluster(adata, df_name='spatial_count_45px', method='kmeans', k=10, label='SC45px_neigh_kmeans_10')

Kmeans clustering

In [7]:
adata.obs

,X_centroid,Y_centroid,core_imageid,cores.x,celltype,Annotation,Stage,patient_id_AB19_1654,Area,Eccentricity,...,antioxidant_TXNRD1,antioxidant_GLUT1,NQO1_GCLC_VIM,celltype_2,celltype_1,Tumor_state,CellCategory,CellID,imageid,SC45px_neigh_kmeans_10
19_02_02A_1,2027.642,1011.2380,core77_19_02_02A,core77,Other,Invasive border,2,AB19-1654_P10158,282,0.821700,...,failed_classify,failed_classify,---,Other,Other.Stroma,Other.Stroma,Stroma,1,19_02_02A,4
19_02_01A_10,5871.136,777.1124,core77_19_02_01A,core77,Tumor,Tumor center,2,AB19-1654_P10117,258,0.620470,...,TXNRD1_pos,failed_classify,+--,Tumor_+--,Tumor,Tumor,Tumor,10,19_02_01A,2
19_02_02A_10,1999.424,1195.5040,core77_19_02_02A,core77,CD68.Macrophages,Invasive border,2,AB19-1654_P10158,125,0.755401,...,failed_classify,failed_classify,+--,CD68.Macrophages,CD68.Macrophages,CD68.Macrophages,Immune,10,19_02_02A,4
19_02_01A_100,6136.928,858.5450,core77_19_02_01A,core77,Tumor,Tumor center,2,AB19-1654_P10117,222,0.803584,...,TXNRD1_pos,failed_classify,+--,Tumor_+--,Tumor,Tumor,Tumor,100,19_02_01A,2
19_02_02A_100,1728.540,1302.0830,core77_19_02_02A,core77,Immune,Invasive border,2,AB19-1654_P10158,300,0.522613,...,failed_classify,failed_classify,---,Immune,Other.Immune,Other.Immune,Immune,100,19_02_02A,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
INF1_99998,36889.410,6446.4120,core22_INF1,core22,Tumor,Inflammation,unknown,AB19-1654_P10648,148,0.641780,...,failed_classify,failed_classify,---,Tumor_---,Tumor,Tumor,Tumor,99998,INF1,2
1B_99999,11181.530,7239.2680,core64_1B,core64,FOXP3.CD4.Tregs,Tumor center,2,AB19-1654_P10561,366,0.771436,...,failed_classify,failed_classify,-++,FOXP3.CD4.Tregs,Treg,Treg,Immune,99999,1B,1
2B_99999,8371.249,6579.8230,core71_2B,core71,CD4.T.cells,Lymph node met,2,AB19-1654_P10599,558,0.863484,...,failed_classify,failed_classify,-++,CD4.T.cells,CD4.T.cells,CD4.T.cells,Immune,99999,2B,1
3B_99999,20828.410,4477.0180,core42_3B,core42,Tumor,Tumor center,1,AB19-1654_P10620,112,0.883622,...,failed_classify,failed_classify,---,Tumor_---,Tumor,Tumor,Tumor,99999,3B,2
INF1_99999,36941.910,6450.2230,core22_INF1,core22,Tumor,Inflammation,unknown,AB19-1654_P10648,479,0.646270,...,failed_classify,failed_classify,---,Tumor_---,Tumor,Tumor,Tumor,99999,INF1,2

In [7]:
# First, create a mapping DataFrame from adata.obs with the columns we need
mapping_df = adata.obs[['CellID', 'core_imageid', 'SC45px_neigh_kmeans_10']]

# Reset the index of data if CellID is currently the index
data_reset = data.reset_index()

# Merge data with the mapping DataFrame using CellID as the key
merged_data = data.merge(mapping_df, on=['CellID', 'core_imageid'], how='left')

# Set CellID back as the index if needed
data = merged_data.set_index('CellID')

In [8]:
data

,S9.6,HER3,panCK,SMA,CD45,Ki67_2,CD4,FOXP3,CD8a,CD11b,...,antioxidant_GCLC,antioxidant_TXNRD1,antioxidant_GLUT1,NQO1_GCLC_VIM,celltype_2,celltype_1,Tumor_state,GCLC_VIM,CellCategory,SC45px_neigh_kmeans_10
CellID,,,,,,,,,,,,,,,,,,,,,
1,0.587351,0.668424,0.197573,0.119095,0.357855,0.221494,0.351031,0.261670,0.120537,0.641891,...,failed_classify,failed_classify,failed_classify,---,Other,Other.Stroma,Other.Stroma,Other.Stroma,Stroma,4
10,0.711467,0.738836,0.522747,0.185507,0.275963,0.214838,0.374685,0.350623,0.029450,0.608733,...,failed_classify,TXNRD1_pos,failed_classify,+--,Tumor_+--,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor,2
10,0.803970,0.824031,0.331924,0.204348,0.355699,0.234078,0.518679,0.390894,0.161177,0.666724,...,failed_classify,failed_classify,failed_classify,+--,CD68.Macrophages,CD68.Macrophages,CD68.Macrophages,CD68.Macrophages,Immune,4
100,0.744246,0.762114,0.531392,0.185345,0.246533,0.227313,0.392369,0.348677,0.023832,0.619029,...,failed_classify,TXNRD1_pos,failed_classify,+--,Tumor_+--,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor,2
100,0.796639,0.796858,0.357244,0.192493,0.431782,0.228827,0.489430,0.380457,0.156145,0.674359,...,failed_classify,failed_classify,failed_classify,---,Immune,Other.Immune,Other.Immune,Other.Immune,Immune,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99998,0.832069,0.723583,0.638020,0.130660,0.135379,0.173406,0.316902,0.220026,0.366662,0.634752,...,failed_classify,failed_classify,failed_classify,---,Tumor_---,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor,2
99999,0.770561,0.929819,0.451729,0.390374,0.620998,0.488494,0.532568,0.522331,0.467017,0.871813,...,GCLC_pos,failed_classify,failed_classify,-++,FOXP3.CD4.Tregs,Treg,Treg,Treg,Immune,1
99999,0.678946,0.721054,0.228812,0.598502,0.598347,0.229858,0.528080,0.499220,0.232839,0.704152,...,GCLC_pos,failed_classify,failed_classify,-++,CD4.T.cells,CD4.T.cells,CD4.T.cells,CD4.T.cells,Immune,1
99999,0.845231,0.699380,0.353627,0.224872,0.146464,0.184371,0.271080,0.261490,0.140438,0.615633,...,failed_classify,failed_classify,failed_classify,---,Tumor_---,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor,2
99999,0.733093,0.744165,0.681137,0.123724,0.095359,0.169273,0.324368,0.219458,0.318816,0.638407,...,failed_classify,failed_classify,failed_classify,---,Tumor_---,Tumor,Tumor,Tumor.GCLC-VIM-,Tumor,2

In [9]:
rename_dict = {'RCN1': ['2'],
               'RCN2': ['1'],
               'RCN3': ['4'],
               'RCN4': ['6'],
               'RCN5': ['7'],
               'RCN6': ['0'],
               'RCN7': ['3'],
               'RCN8': ['5'],
               'RCN9': ['8'],
               'RCN10': ['9']
                }

replace_dict= {v: k for k, values in rename_dict.items() for v in values}
data['SC45px_neigh_kmeans_10'] = data['SC45px_neigh_kmeans_10'].astype(str)
data['RCNs'] = data['SC45px_neigh_kmeans_10'].replace(replace_dict)

In [10]:
data.to_csv('/Users/wenqchen/Desktop/Projects/Auria/Data/t-CycIF/Data_AllMarkers_filtered_RCNs.csv')